Add Vesting to Asset Hubs
polkadot-fellows/runtimes pull request #269
Opened 2024-04-09 09:11 UTC by joepetrowski

Adds the Vesting pallet to the Asset Hub runtimes, as a few people have requested this feature, and in general the Asset Hubs should provide more balances/asset-related features than the Relay Chain.

2024-04-09 16:50 UTC, joepetrowski commented on system-parachains/asset-hubs/asset-hub-kusama/src/lib.rs
> +	type BlockNumberProvider = System;
TODO: Switch to Relay Chain

2024-04-12 03:03 UTC, xlc commented
Why will anyone else other than W3F want to perform vested transfer of DOT? When people requesting vesting, presumably they want to vest transfer assets in pallet-assets, not the relaychain token.

2024-04-12 05:05 UTC, joepetrowski commented
> Why will anyone else other than W3F want to perform vested transfer of DOT? When people requesting vesting, presumably they want to vest transfer assets in pallet-assets, not the relaychain token.

For one, the person who requested this was from Talisman, not W3F, for DOT.

Two, it would be great if Parity and W3F used Asset Hub instead of the Relay Chain for vested DOT transfers.

Three, yes I understand the demand for vested transfers of assets. This PR does not prevent that.

2024-04-12 10:08 UTC, acatangiu commented
> Why will anyone else other than W3F want to perform vested transfer of DOT? When people requesting vesting, presumably they want to vest transfer assets in pallet-assets, not the relaychain token.

I agree we _also_ need vesting for pallet-assets instances too, not just pallet-balances.

example community request: https://github.com/paritytech/polkadot-sdk/issues/4090

2024-04-12 10:09 UTC, acatangiu requested changes
add vesting to pallet-assets instances too

2024-04-12 10:54 UTC, joepetrowski commented
> add vesting to pallet-assets instances too

That is the plan, but the Vesting pallet requires something with `LockableCurrency`, which `pallet-assets` does not implement. In order to have vesting for assets, we need:

1. Migration of Vesting pallet from `Currency` to `Fungible`;
2. An implementation of `fungible::freeze` for `pallet-assets` (https://github.com/paritytech/polkadot-sdk/pull/3951)

I don't think we should block the feature of vesting DOT on waiting for these. Asset vesting will probably be another instance of the Vesting pallet anyway, so they have no overlap.

2024-04-12 11:48 UTC, acatangiu approved these changes
adding vesting in two steps: this PR pallet-balances, future PR pallet-assets is fine

2024-04-12 20:09 UTC, bkchr approved these changes

2024-04-15 04:54 UTC, joepetrowski commented
/merge

2024-04-15 04:55 UTC, merged