set Encointer target blocktime to 6s
polkadot-fellows/runtimes pull request #462
Opened 2024-09-26 14:33 UTC by brenzi

Encointer communities could benefit from 6s block time because the network is used for IRL point-of-sale or person-to-person transactions

Encointer is unaffected by https://github.com/paritytech/polkadot-sdk/issues/3268 as its pallets have since ever based time on block timestamps

The parameters are copy-paste from people, as introduced by #308

2024-09-26 18:21 UTC, clangenb commented on system-parachains/encointer/src/lib.rs
> +pub const UNINCLUDED_SEGMENT_CAPACITY: u32 = 2;
I have seen and implemented 3 for the unincluded segment capacity, but I remember learning that 3 and 2 actually resolve to the same value of 6s blocktime in the end.

2024-09-30 07:27 UTC, eskimor approved these changes
Looks good.

2024-09-30 11:35 UTC, brenzi commented
CI fail out-of-scope: Check Migrations / check-migrations (asset-hub-kusama
but I can't trigger a re-run. Who could trigger that?

2024-10-01 07:57 UTC, bkchr commented
@brenzi all the pallets you are using, none of them has scheduled anything based on blocks? Maybe your democracy or similar? You will produce twice as many blocks, meaning that anything that is using blocks for scheduling will happen twice as fast.

2024-10-01 07:57 UTC, joepetrowski approved these changes

2024-10-01 07:57 UTC, joepetrowski commented on CHANGELOG.md
> +- Change target block time for Encointer to 6s
```suggestion
- Change target block time for Encointer to 6s ([polkadot-fellows/runtimes#462](https://github.com/polkadot-fellows/runtimes/pull/462))
```

2024-10-01 07:58 UTC, joepetrowski requested changes
Just removing my review for Basti's comment due to auto-merge.

2024-10-01 11:22 UTC, brenzi commented
@bkchr I'm pretty sure we're fine:
* encointer_scheduler: schedules cycles based on block timestamps
* encointer_democracy: evaluates proposal timings based on timestamps
* encointer_balances: demurrage is defined per block and will effectively be doubled. However, demurrage rates can be changed by Encointer council, so state migration could be skipped. As I observed the peoplechain for a while, I saw that the average block time was in between 6 and 12s. I think it is reasonable to apply 6s target now and then adjust demurrage based on actual block time statistics when all went well.

2024-10-01 11:26 UTC, kianenigma reviewed
Can you please check if the instructions in https://paritytech.github.io/polkadot-sdk/master/polkadot_sdk_docs/guides/async_backing_guide/index.html are enough to create this PR?

2024-10-01 11:32 UTC, brenzi commented
@kianenigma that document encompasses much more than this PR and Encointer benefitted from many other PR's in this repo that did all the prep work around async backing. In this PR I basically just needed to change constants - and there the linked docs are fine

2024-10-01 11:41 UTC, brenzi commented
/merge

2024-10-01 12:04 UTC, bkchr commented
Ty @brenzi. If you are using timestamps, it should all be good :)

2024-10-01 14:36 UTC, joepetrowski approved these changes

2024-10-01 15:37 UTC, merged